services:
  - type: web
    name: guessing-game
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python guess.py
    envVars:
      - key: FLASK_ENV
        value: production
    plan: free
